name: Moustafa Bahaa
tagline: ML / DL and computer vision engineer.
career-objective: I am passionate about AI research. #, with a particular focus on improving embodied reasoning of multimodal models. #I am also keenly interested in Continual Learning and Agentic systems.
color-theme: red #blue # red or blue
avatar-filename: my_avatar.png # Change to your avatar's filename
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: eng.mostafabahaa25@gmail.com
  github: 
    visibility: true
    handle: msotafabahaa25
  linkedin: 
    visibility: true
    handle: mostafa-bahaa-32765a221
  twitter: 
    visibility: false
    handle: Mostafa
  scholar:
    visibility: false
    handle:
    
# Collections
collections:
  education:
    output: true
    sort_by: order
  experience:
    output: true
    sort_by: order
  achievements:
    output: true
    sort_by: order
  publications:
    output: false
    sort_by: year
  projects:
    output: true
    sort_by: order
  skills:
    output: true
    sort_by: order
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: true
    sort_by: year

# About Page Options
collection_option:
  education: 
    label: Education
    visibility: true
  experience: 
    label: Experience
    visibility: true
  achievements: 
    label: Achievements
    visibility: true
  publications: 
    label: Publications
    visibility: false
  projects: 
    label: Projects ("What I can not create I do not understand", R.F)
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Certifications
    visibility: true
navigation:
- title: About
  url: /
# - title: Blog
#   url: /blog/
# - title: Contact
#   url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  # - scope:
  #     path: ''
  #     type: publications
  #   values:
  #     permalink: /publications/:title
  #     layout: publication
  #     comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X
